version: '3'

services:
  db:
    container_name: postgres-local
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: scott
      POSTGRES_PASSWORD: tiger
      POSTGRES_DB: mytest
    volumes:
      - ./docker-volumes/postgres-data:/var/lib/postgresql/data